name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore DotNetSelenium/DotNetSelenium.csproj

    - name: Build project
      run: dotnet build DotNetSelenium/DotNetSelenium.csproj --no-restore

    - name: Run tests
      run: dotnet test DotNetSelenium/DotNetSelenium.csproj --no-build