jobs:
  build-and-test:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh  # force PowerShell instead of bash

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore DotNetSelenium\DotNetSelenium.csproj

    - name: Build
      run: dotnet build DotNetSelenium\DotNetSelenium.csproj --no-restore

    - name: Test
      run: dotnet test DotNetSelenium\DotNetSelenium.csproj --no-build