name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Restore
      run: dotnet restore DotNetSelenium/DotNetSelenium.csproj

    - name: Build
      run: dotnet build DotNetSelenium/DotNetSelenium.csproj --no-restore

    - name: Run Tests
      run: dotnet test DotNetSelenium/DotNetSelenium.csproj --no-build --verbosity normal
      env:
        DISPLAY: :99
